# Generated by Django 6.0.1 on 2026-01-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vercel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="receipt_image",
            field=models.ImageField(blank=True, null=True, upload_to="receipts/"),
        ),
    ]
