# Generated by Django 6.0.1 on 2026-01-26 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vercel", "0002_order_receipt_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "booking_id",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("product_name", models.CharField(max_length=200)),
                ("quantity", models.IntegerField(default=1)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "รอยืนยัน"),
                            ("confirmed", "ยืนยันแล้ว"),
                            ("converted", "แปลงเป็นคำสั่งซื้อ"),
                            ("cancelled", "ยกเลิก"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vercel.customer",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Bookings",
                "ordering": ["-created_at"],
            },
        ),
    ]
