# Generated by Django 6.0.1 on 2026-01-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vercel", "0004_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("hat", "หมวก"),
                    ("shoes", "รองเท้า"),
                    ("clothes", "เสื้อผ้า"),
                    ("accessories", "เครื่องประดับ"),
                    ("equipment", "อุปกรณ์"),
                ],
                max_length=50,
            ),
        ),
    ]
