# Generated by Django 5.2.6 on 2026-01-30 06:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vercel", "0006_contactmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discount_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="ลดราคาเป็นเปอร์เซ็นต์ (0-100)",
                max_digits=5,
            ),
        ),
    ]
